name: food_classification_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.5.1
  - torchvision=0.20.1
  - pymongo=4.6.2
  - pillow=11.1.0
  - matplotlib=3.7.2
  - numpy=2.2.2
  - pip=23.0
  - pip:
    - azureml-defaults
    - azureml-core
    - inference-schema